# Generated by Django 2.1.5 on 2019-01-29 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phase1', '0001_initial'),
    ]
    atomic=False
    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('news_pic', models.ImageField(blank=True, upload_to='news_pic')),
                ('short_desc', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=2000)),
                ('fb_link', models.URLField(default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ClubFollowers',
            new_name='ClubFollower',
        ),
        migrations.RenameModel(
            old_name='ClubMembers',
            new_name='ClubMember',
        ),
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
        migrations.AddField(
            model_name='news',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase1.Club'),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
