# Generated by Django 2.1.5 on 2019-01-29 21:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phase1', '0002_auto_20190130_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('event_pic', models.ImageField(blank=True, upload_to='event_pic')),
                ('short_desc', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=2000)),
                ('venue', models.CharField(default='', max_length=2000)),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase1.Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
