# Generated by Django 2.1.5 on 2019-01-30 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('is_cumpulsory_update', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
