# Generated by Django 2.1.7 on 2019-03-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='club',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
