# Generated by Django 2.1.7 on 2019-03-04 07:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('event_pic', models.ImageField(blank=True, upload_to='event_pic')),
                ('short_desc', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=2000)),
                ('venue', models.CharField(default='', max_length=2000)),
                ('event_start_date', models.DateField(default=datetime.date.today)),
                ('event_end_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
        ),
    ]
