ci='club_id'
ei='email_id'
ia='is_admin'
name_='name'
email_='email'
password_='password'
otp_='otp'
new_password_='new_password'
title_='title'
sd_='short_desc'
desc_='description'
np_='news_pic'
venue_='venue'
ep_='event_pic'
ed_='event_date'

